### PR TITLE
Fix h2g_valid assertion error on 64-bit guest

### PR DESCRIPTION
**Pull request by mpbagot**
This PR fixes the h2g_valid error which occurs when running certain 64 bit applications in Hangover. This error is first noted in issue #46. The h2g_valid assertion fails in two places, at windows-user/main.c:650 and windows-user/main.c:462.

The first of these results from the ret_code pointer in qemu_execute, whilst second is caused by the wrapper pointer passed to qemu_execute in call_dll_entry_point.

These changes have only been tested on an Aarch64 Linux build of Hangover.

### CODE REVIEW

**Comment by stefand** [comment]
Hi,

Thanks for the patch, and debugging this issue. The patch looks harmless, although I'd like to understand what is going on before accepting it. If my suspicion is right then it would be better fixed elsewhere.

At what address is the qemu.so binary loaded? You can get it either from /proc/<pid>/maps or by printing an address, like the bad static data. Qemu has TARGET_VIRT_ADDR_SPACE_BITS 47 for x86_64 guests, which is probably correct for 64 bit Linux, but not 64 bit windows - on Windows user address space is limited to 44 bit.

Wine already has plenty of code to set up the address space to match that of Windows. This is in wine/loader/preloader.c. Wine will set things up like an aarch64 Windows, which may be different from an x86_64 Windows. So qemu should (in theory, bugs nonwithstanding) be loaded at an address that's valid for aarch64 Windows.

It's hangover's job to make the aarch64 Windows address space look like x86 / x86_64. The x86_64 part is implemented already, but I didn't run into the need for x86_64 setups.

So ideally we should verify that the things Wine currently does are correct for aarch64 and add code to block higher addresses ourselves like we do for 32 bit apps. Then we can define TARGET_VIRT_ADDR_SPACE_BITS to 64 to tell qemu we're taking care of this stuff ourselves. It's OK if qemu resides outside the normal x86_64 user address space because no Windows application will call it directly, and for our code we just shouldn't play any games with the "unused" pointer bits.

This may all be too advanced for the little fun project hangover is, so maybe we should just define TARGET_VIRT_ADDR_SPACE_BITS to 64, close our eyes and hope for the best.

**Comment by mpbagot** [comment]
Based on the maps file, the qemu binary is loaded in 5 parts, each part with different permissions. The file begins at 0xffff912e4000 and ends at 0xffff9153f000. The related section is embedded below:
```
ffff912e4000-ffff91360000 r-xp 00000000 b3:02 1289089                    /home/ubuntu/build/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so
ffff91361000-ffff914fb000 r-xp 0007d000 b3:02 1289089                    /home/ubuntu/build/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so
ffff914fb000-ffff914fc000 ---p 00217000 b3:02 1289089                    /home/ubuntu/build/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so
ffff914fc000-ffff9152f000 r--p 00217000 b3:02 1289089                    /home/ubuntu/build/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so
ffff9152f000-ffff9153f000 rw-p 0024a000 b3:02 1289089                    /home/ubuntu/build/hangover/build/qemu/x86_64-windows-user/qemu-x86_64.exe.so
```

**Comment by stefand** [comment]
Indeed, that would still be within (1 << 47) - 1). Can you print the address of the static const ret code?

**Comment by mpbagot** [comment]
The exact addresses varied slightly with each run, but the first value recorded for each variable is listed below:

x86_64_wrapper = 0xffffa4924f50
i386_wrapper = 0xffff9377af70
wrapper = 0x555c0
ret_code64 = 0xffffa49ba7f8
ret_code32 = 0xffff93779d50
ret_code = 0x555f0

**Pull request closed without merging**
